ON_PROGRESS, SUCCESS, FAILED, UNSTARTED = ("ON_PROGRESS", "SUCCESS", "FAILED", "UNSTARTED")
STATUS_OPTIONS = (
    (ON_PROGRESS, "ON_PROGRESS"),
    (SUCCESS, "SUCCESS"),
    (FAILED, "FAILED"),
    (UNSTARTED, "UNSTARTED")
)
