ON_PROGRESS, SUCCESS, FAILED, UNSTARTED = ("ON_PROGRESS", "SUCCESS", "FAILED", "UNSTARTED")
STATUS_OPTIONS = (
    (ON_PROGRESS, "ON_PROGRESS"),
    (SUCCESS, "SUCCESS"),
    (FAILED, "FAILED"),
    (UNSTARTED, "UNSTARTED")
)

MOBILE_NET, YOLO, FASTERRCNN, MASKRCNN = ("MOBILE_NET", "YOLO", "FASTERRCNN", "MASKRCNN")
MODEL_NAME = (
    (MOBILE_NET, "MOBILE_NET"),
    (YOLO, "YOLO"),
    (FASTERRCNN, "FASTERRCNN"),
    (MASKRCNN, "MASKRCNN")
)
