# Generated by Django 3.2.15 on 2022-09-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AisiaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ON_PROGRESS', 'ON_PROGRESS'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('UNSTARTED', 'UNSTARTED')], default='FAILED', max_length=12, null=True)),
                ('model_name', models.CharField(choices=[('MOBILE_NET', 'MOBILE_NET'), ('YOLO', 'YOLO'), ('FASTERRCNN', 'FASTERRCNN'), ('MASKRCNN', 'MASKRCNN')], max_length=16)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('time_needed', models.IntegerField(blank=True, default=0, null=True)),
                ('model_accuracy', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'aisia_state',
            },
        ),
    ]
